apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myappsts
  labels: 
     for: web
spec:
   template:
    metadata:
      name: webapp
      labels:
        for: webapp
    spec:
       containers:
        - name: nginxcon
          image: nginx
   selector:
      matchLabels:
        for: webapp
            
   serviceName: stsservice
