apiVersion: v1
kind: Service 
metadata:
  name: first-cip
  labels:
     type: cip-1
  namespace: test-ns
spec:
   type: ClusterIP
   selector:
     app: nginx
   ports:
     - port: 80
       targetPort: 80