kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted-rolebinding
  namespace: default
subjects:
- kind: User
  name: $(Service Account name)
  namespace: default
roleRef:
  kind: ClusterRole
  name: cicd-deployer
  apiGroup: rbac.authorization.k8s.io