apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkinsrolebind
subjects:
  - kind: User
    name: jenkins
    apiGroup: rbac.authorization.k8s.io
roleRef:
   kind: Role 
   name: jenkinsrole
   apiGroup: rbac.authorization.k8s.io