apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkinsrole
rules:
  - apiGroups: [""]
    resources:
      - "pods"
      - "services"
      - "namespaces"
    verbs:
       - "*"
  - apiGroups:
    - "apps"
    resources:
      - "deployment"
      - "statefulset"
    verbs:
      - "*"
