apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
 name: cicd-deployer
rules:
- apiGroups:
  - extensions
  - apps
  - ""  
  resources:
  - containers
  - endpoints
  - services
  - pods
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
