apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: webpvc
spec:
    accessModes:
     ['ReadWriteOnce']
    resources:
       requests:
          storage: 10Gi
    storageClassName: web-sc

    